// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUPq-stzfnQEx6xpX7pak0z6fGMPpf0Wc',
    appId: '1:903853458722:web:4b105e72fdcaef57cad17b',
    messagingSenderId: '903853458722',
    projectId: 'success-subliminals-5bc44',
    authDomain: 'success-subliminals-5bc44.firebaseapp.com',
    storageBucket: 'success-subliminals-5bc44.appspot.com',
    measurementId: 'G-V3YEKNHK0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCAreyu9Tjddhs7O267e1KTWLV-5IiMm4',
    appId: '1:903853458722:android:f18bdd3c1fe39528cad17b',
    messagingSenderId: '903853458722',
    projectId: 'success-subliminals-5bc44',
    storageBucket: 'success-subliminals-5bc44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQmFbEmn_sGdsWWvUK8owSSRn4a5L8vY',
    appId: '1:903853458722:ios:c7030ce5488ce483cad17b',
    messagingSenderId: '903853458722',
    projectId: 'success-subliminals-5bc44',
    storageBucket: 'success-subliminals-5bc44.appspot.com',
    iosClientId:
        '903853458722-keg1tui7ogcgru140leg8qf7hihi2kqn.apps.googleusercontent.com',
    iosBundleId: 'com.subliminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZQmFbEmn_sGdsWWvUK8owSSRn4a5L8vY',
    appId: '1:903853458722:ios:cff8a9fb2f948860cad17b',
    messagingSenderId: '903853458722',
    projectId: 'success-subliminals-5bc44',
    storageBucket: 'success-subliminals-5bc44.appspot.com',
    iosClientId:
        '903853458722-37o7hetbevbd6dksg1oncpbgfmvp2mkt.apps.googleusercontent.com',
    iosBundleId: 'com.successsubliminal.successSubliminal',
  );

/*import 'package:firebase_core/firebase_core.dart';
  import 'firebase_options.dart';

// ...

  await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
  );*/
}
